[package]
name = "fireworks"
version = "0.1.0"
authors = ["James Duerden <james@jamieduerden.me>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
diesel = { version = "1.0.0", features = ["postgres", "mysql"] }
dotenv = "0.9.0"
